"""
SANJEEVNI - convert the trained edge model to int8 TensorFlow Lite and
write the C header the ESP32 firmware compiles in (B19: this step was
referenced by edge_model_data.h as "quantize_model.py" but never committed).

Run in the folder where train_edge_model.py wrote edge_model.keras and
scaler_params.json (see make_edge_dataset.py for the full sequence).
Writes edge_model_int8.tflite and edge_model_data.h, and prints the
EDGE_FEATURE_MEAN / EDGE_FEATURE_SCALE lines for edge_ai.h.
"""

import json

import numpy as np
import tensorflow as tf


def representative_data(X_scaled, samples=500):
    # Lets the converter pick int8 ranges from realistic inputs
    idx = np.random.default_rng(0).choice(len(X_scaled), size=min(samples, len(X_scaled)), replace=False)
    for i in idx:
        yield [X_scaled[i:i + 1]]


def to_c_header(model_bytes: bytes) -> str:
    rows = [", ".join(f"0x{b:02x}" for b in model_bytes[i:i + 12]) for i in range(0, len(model_bytes), 12)]
    body = ",\n  ".join(rows)
    return (
        "// Auto-generated by quantize_edge_model.py from edge_model_int8.tflite - do not edit.\n"
        "// Regenerate with the steps in make_edge_dataset.py if the model is retrained.\n\n"
        "#ifndef EDGE_MODEL_DATA_H\n#define EDGE_MODEL_DATA_H\n\n"
        f"const unsigned int edge_model_data_len = {len(model_bytes)};\n"
        f"alignas(8) const unsigned char edge_model_data[] = {{\n  {body}\n}};\n\n#endif\n"
    )


def main():
    model = tf.keras.models.load_model("edge_model.keras")
    with open("scaler_params.json") as f:
        scaler = json.load(f)
    mean, scale = np.array(scaler["mean"]), np.array(scaler["scale"])
    X = np.load("edge_X.npy")
    X_scaled = ((X - mean) / scale).astype(np.float32)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = lambda: representative_data(X_scaled)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    tflite_model = converter.convert()

    with open("edge_model_int8.tflite", "wb") as f:
        f.write(tflite_model)
    with open("edge_model_data.h", "w") as f:
        f.write(to_c_header(tflite_model))

    fmt = lambda values: ", ".join(f"{v:.7f}f" for v in values)
    print(f"wrote edge_model_int8.tflite and edge_model_data.h ({len(tflite_model)} bytes)")
    print("paste into Arduino/sanjeevni_lora_node/edge_ai.h:")
    print(f"static const float EDGE_FEATURE_MEAN[5] = {{{fmt(mean)}}};")
    print(f"static const float EDGE_FEATURE_SCALE[5] = {{{fmt(scale)}}};")


if __name__ == "__main__":
    main()
